alias: hourly_routine.yaml
description: Master controller for all scripts that run on a 1-hour cycle
triggers:
  - hours: /1
    minutes: "00"
    seconds: "00"
    trigger: time_pattern
conditions:
  - condition: time
    after: "06:00:00"
    before: "22:00:01"
actions:
  - alias: Run Battery Check
    action: script.check_device_batteries
    data: {}
mode: parallel
max: 10
