alias: quarter_hourly_routine.yaml
description: "Master controller running every 15 mins"
triggers:
  - trigger: time_pattern
    minutes: "/15"
actions:
  - alias: "Update Sleep State"
    # Matches the script entity ID created by your filename/alias
    action: script.is_user_sleeping_yaml
mode: parallel
max: 10